---
title: "Compilador de Snippets"
format: 
  pdf:
    pdf-engine: pdflatex
    papersize: "a4"
    documentclass: book
    toc: true
    lang: es-PE
    number-sections: true
    margin-left: "3.5cm"
    margin-right: "2.5cm"
    margin-top: "2.5cm"
    margin-bottom: "2.5cm"
---

# R base
## Instalación y Configuración
```{powershell}
# PowerShell
Write-Host "¡Hola desde PowerShell en Quarto!"
```
## Comandos Básicos
```{r}
#| eval: true
#| echo: true
#| message: false
#| warning: false
#| code-fold: false
#| code-summary: "Mostrar/Ocultar Código"

# Libreria
library(tidyverse)
# Exploración de estructura
mpg %>% str()
# Regresion Lineal
lm(displ~drv+year,mpg) %>% summary()
```
## Ggplot
## Animaciones
## Dplyr
## Metaprogramación
## Mapas 
## Bash

# C\# 
## Instalación y Configuración
## Comandos Básicos
## Vectores y Matrices
## Listas y Enumerables
## LINQ
## POO

# C# + R
## Instalación y Configuración
## Comandos Básicos

# C++
## Instalación y Configuración
## Comandos Básicos
```{cpp}
#include <iostream>
#include <cmath>
#include <string>
#include <conio.h>

using namespace std;

int MyFunc(int x);

int main(int argc, char const *argv[])
{
  int rep = 0;
  cout << "\nIngresa el # de repeticiones: ";
  cin >> rep;
  MyFunc(rep);
  getch();
  return 0;
}

int MyFunc(int x)
{
  cout << "\n";
  for (int i = 0; i <= x; i++)
  {
    cout << " N " << i << " --> " << pow(i, 2) << "\n";
  }  
  cout << "\n";
  return 0;
}
```
## Vectores y Matrices
## Listas y Enumerables
## POO

# Base de Datos
## MySql
## PostgreSql
## T-Sql

# Blazor
## Blazor Web Assembly
## Blazor Server
## Blazor Minimal Api
## Blazor Hosted
## Blazor + R

# Ubuntu
## Instalación
## Comandos Básicos
## Usuarios y Permisos
## Administración de Discos
## Red y Puertos
## Administración de Servidor

# Docker
## Comandos Básicos

## Nginx + Html

## Nginx + Minimal Api
### Nginx + Mininmal Api + MySql + R
### Nginx + Mininmal Api + PostgreSql + R
### Nginx + Mininmal Api + SqlServer + R

## Nginx + Blazor Hosted
### Nginx + Blazor Hosted + MySql + R
### Nginx + Blazor Hosted + PostgreSql + R
### Nginx + Blazor Hosted + SqlServer + R